# site settings
title: 阿纳金
subtitle: 技术博客
email: wangwenbineddie@126.com
description: 中国地震局工程力学研究所
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address:西大直街
city: 哈尔滨
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings

# build settings
markdown: kramdown

sass:
  style: compressed
